---
title: "Data_Cleaning"
output: word_document
---
离散数值变量转化为类别变量，并加上标签,需要使用car包

```{r factor recode discrete}
school <- c(2, 1, 1, 2, 0, 1, 1,3,3,5,4,35,6,5,8)
#recode接收的参数:第一个是一个数值变量，第二个参数是归类参数
#lo表示最小值,hi标示最大值，但是必须用在lo:5,7:hi这样的仿序列语法里
#c(5,8)也是允许的，但是c(5,8,1:3)这样的语法是不行的，作者没定义
#else表示所有没匹配的
#最后的参数as.factor.result如果不设置，默认结果是一个string向量

f1_school<-recode(school,"lo:1='law';2:3='business';4='trade';c(5,8)='finance';10:hi='art';else=NA",
               as.factor.result=TRUE,
               levels=c("law","business","finance","trade","art"))

f2_school<-recode(school,"lo:1='law';2:3='business';4='trade';c(5,8)='finance';10:hi='art';else=NA",
               as.factor.result=TRUE)
f1_school
f2_school

```
连续数值变量编码为factor变量，并加上标签
```{r factor recode continous}
#模拟的数据distance是路段到A点的距离，gas_stations是路段上加油站数
#要做的事是先根据距离把distance划分为近、中、远，然后分别汇总统计加油站数

distance<-rnorm(20)*100
gas_stations<-sample(20)
df<-data_frame(distance,gas_stations)
summary(distance)
df$abs_dis<-abs(df$distance)
df$dist_class<-cut(df$abs_dis,breaks=c(0,20,50,100,1000),
                   right=TRUE,
                   ordered_result=TRUE)
df$dist_class

aggregate(df$gas_stations,list(df$dist_class),sum)

```

数据缩尾处理Winsorize，去除数据里的异常值，一般默认去掉1%双侧
这个有些包里有此函数，但是专门调用个包不值得，自己参考网络写了个

```{r Winsor}
#winsor函数定义
winsor<-function(x,p=0.01) {
   if(length(p) != 1 || p < 0 || p > 0.5) {
      stop("bad p-value for winsorization")
   }
   lim <- quantile(x, probs=c(p, 1-p))
   x[ x < lim[1] ] <- lim[1]
   x[ x > lim[2] ] <- lim[2]
   return(x)
}
#用AER包里地CPS1985演示对wage，age，education进行0.05缩尾
data(CPS1985)
summary(CPS1985$wage)
n_cps<-as.data.frame(sapply(select(CPS1985,wage,age,education),winsor,p=0.05))
summary(n_cps$wage)

```






